stages:
  - build
  - deploy

variables:
  CONTAINER_NAME: 'discordbot'
  PORT: 8445
  MAIN_CD_BRANCH: main

build image:
  image: $CI_DOCKER_IMAGE
  stage: build
  tags:
    - build
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $MAIN_CD_BRANCH'
      when: always
    - when: never
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - cp ${PROD_ENV} .env
    - cp ${PROD_ENV_ENC} .env.enc
    - docker build . -t $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  needs:
    - build image
  tags:
    - deploy
  interruptible: false
  rules:
    - if: '$CI_COMMIT_BRANCH == $MAIN_CD_BRANCH'
      when: on_success
    - when: never
  script:
    - docker compose down
    - docker compose up -d