version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: gitlab_notifications
    restart: always
    environment:
      POSTGRES_USER: axadmin
      POSTGRES_PASSWORD: DontEatWatermelons
      POSTGRES_DB: gitlab_notifications
    ports:
      - "2326:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
