version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: gitlab_notifications
    restart: always
    environment:
      POSTGRES_USER: axadmin
      POSTGRES_PASSWORD: DontEatWatermelons
      POSTGRES_DB: gitlab_notifications
    ports:
      - '2326:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  discordbot:
    image: $CI_REGISTRY_IMAGE:latest
    container_name: $CONTAINER_NAME
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: axadmin
      DB_PASSWORD: DontEatWatermelons
      DB_NAME: gitlab_notifications
    ports:
      - '$PORT:8444'

volumes:
  postgres_data:
    driver: local
