export enum ENVIRONMENT_KEY {
  TYPEORM_FORCE = 'TYPEORM_FORCE',
  TYPEORM_LOGGING = 'TYPEORM_LOGGING',
  TYPEORM_AUTO_LOAD_ENTITY = 'TYPEORM_AUTO_LOAD_ENTITY',
  POSTGRES_SCHEMA = 'POSTGRES_SCHEMA',
  POSTGRES_DB = 'POSTGRES_DB',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
}
