export enum ENVIRONMENT_KEY {
  TYPEORM_FORCE = 'TYPEORM_FORCE',
  TYPEORM_LOGGING = 'TYPEORM_LOGGING',
  TYPEORM_AUTO_LOAD_ENTITY = 'TYPEORM_AUTO_LOAD_ENTITY',

  POSTGRES_SCHEMA = 'POSTGRES_SCHEMA',
  POSTGRES_DB = 'POSTGRES_DB',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',

  TELEGRAM_CHAT_ID = 'TELEGRAM_CHAT_ID',
  MESSAGE_THREAD_ID = 'MESSAGE_THREAD_ID',

  GITLAB_TOKEN = 'GITLAB_TOKEN',
  GITLAB_BASE_HOST = 'GITLAB_BASE_HOST',
  GITLAB_API_POSTFIX = 'GITLAB_API_POSTFIX',

  DISCORD_WEBHOOK = 'DISCORD_WEBHOOK',

  USE_DISCORD = 'USE_DISCORD',
  USE_TELEGRAM = 'USE_TELEGRAM',
}
